project:
  type: website
  output-dir: docs

website:
  title: "Sakhil Goel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - contact.qmd
      - text: "CV"
      - href: Sakhil Goel - CV.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

